<a href="https://colab.research.google.com/github/akhilps45/Machine_Learning_Models/blob/main/Regularization_Lasso_Ridge_Elasticnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('/content/Advertising.csv')

In [3]:
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
data.isna().sum()

Unnamed: 0    0
TV            0
radio         0
newspaper     0
sales         0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(0)

In [50]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [51]:
X = data.drop('sales',axis=1)
y = data['sales']

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [53]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [54]:
y_pred = lr.predict(X_test)

In [55]:
y_pred

array([16.58673085, 21.18622524, 21.66752973, 10.81086512, 22.25210881,
       13.31459455, 21.23875284,  7.38400509, 13.43971113, 15.19445383,
        9.01548612,  6.56945204, 14.4156926 ,  8.93560138,  9.56335776,
       12.10760805,  8.86091137, 16.25163621, 10.31036304, 18.83571624,
       19.81058732, 13.67550716, 12.45182294, 21.58072583,  7.67409148,
        5.67090757, 20.95448184, 11.89301758,  9.13043149,  8.49435255,
       12.32217788,  9.99097553, 21.71995241, 12.64869606, 18.25348116,
       20.17390876, 14.20864218, 21.02816483, 10.91608737,  4.42671034,
        9.59359543, 12.53133363, 10.14637196,  8.1294087 , 13.32973122,
        5.27563699,  9.30534511, 14.15272317,  8.75979349, 11.67053724,
       15.66273733, 11.75350353, 13.21744723, 11.06273296,  6.41769181,
        9.84865789,  9.45756213, 24.32601732,  7.68903682, 12.30794356,
       17.57952015, 15.27952025, 11.45659815, 11.12311877, 16.60003773,
        6.90611478])

In [56]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

Testing Error

In [57]:
Testing_error = mean_squared_error(y_test,y_pred)
Testing_error

3.7279283306815105

Training Error

In [58]:
y_pred_train = lr.predict(X_train)
Training_error = mean_squared_error(y_train,y_pred_train)
Training_error

2.4108586545578543

Ridge L2

In [59]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

In [60]:
alphavalues = [1e-15,1e-10,1e-8,1e-4,1e-3,1e-2,1,5,10,20,30,100]
solver_values = ['auto','svd']
r = Ridge()
parameters = {'alpha':alphavalues,'solver':solver_values}
ridge_regressor = GridSearchCV(r,parameters)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20, 30, 100],
                         'solver': ['auto', 'svd']})

In [61]:
ridge_regressor.best_params_

{'alpha': 100, 'solver': 'auto'}

In [62]:
ridge_regressor.score(X_train,y_train)

0.909517572518106

In [63]:
ridge = Ridge(alpha=100,solver='auto')
ridge.fit(X_train,y_train)

Ridge(alpha=100)

In [64]:
y_pred_ridge = ridge.predict(X_test)

In [65]:
y_pred_ridge

array([16.58450279, 21.17204823, 21.6668597 , 10.80265494, 22.2290492 ,
       13.30933946, 21.22338833,  7.39068296, 13.45255531, 15.19567118,
        9.00967841,  6.58242325, 14.44017918,  8.92684129,  9.57894901,
       12.12045412,  8.85868367, 16.24956893, 10.3129012 , 18.83017088,
       19.81160211, 13.67891488, 12.435807  , 21.57838122,  7.67976645,
        5.68530725, 20.94084396, 11.896633  ,  9.1383551 ,  8.48645869,
       12.33682003,  9.99103915, 21.70566119, 12.64253767, 18.26257877,
       20.16233256, 14.1870893 , 21.02961367, 10.91866731,  4.44116874,
        9.60429311, 12.53843302, 10.14435712,  8.13537939, 13.34373926,
        5.28745454,  9.3124346 , 14.15074658,  8.77376412, 11.6650001 ,
       15.64568325, 11.76324864, 13.20501125, 11.05387161,  6.43204144,
        9.86225082,  9.45940651, 24.31609481,  7.68894512, 12.31942639,
       17.58617435, 15.2803797 , 11.46248928, 11.11966621, 16.61195134,
        6.90996172])

In [66]:
te = mean_squared_error(y_test,y_pred_ridge)
te

3.720601493106788

In [67]:
ridge.score(X_train,y_train)

0.909517572518106

Lasso **L1**

In [68]:
from sklearn.linear_model import Lasso
lasso = Lasso()

parameters = {'alpha':[1e-15,1e-10,1e-8,1e-4,1e-3,1e-2,1,5,10,20,30,100]}

lasso_regressor = GridSearchCV(lasso,parameters)
lasso_regressor.fit(X_train,y_train)

GridSearchCV(estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20, 30, 100]})

In [69]:
bp= lasso_regressor.best_params_
bp

{'alpha': 1}

In [70]:
lasso = Lasso(alpha=bp['alpha'])
lasso.fit(X_train,y_train)

Lasso(alpha=1)

In [71]:
y_pred_lasso = lasso.predict(X_test)

In [72]:
y_pred_lasso

array([16.52391951, 21.05821853, 21.624966  , 10.7457245 , 22.18826932,
       13.24310226, 21.16115506,  7.45487482, 13.54176537, 15.19735958,
        9.05895919,  6.64726211, 14.41534178,  8.94924498,  9.65557133,
       12.16355273,  8.83613562, 16.27480625, 10.32558284, 18.84483264,
       19.71142443, 13.51103813, 12.41920349, 21.46659417,  7.77792701,
        5.7752475 , 20.87123457, 11.95956215,  9.18798248,  8.52886947,
       12.41703422, 10.02587396, 21.57497619, 12.493691  , 18.27719607,
       20.16422674, 14.15387342, 20.96077769, 10.98977443,  4.53493832,
        9.66985435, 12.62189921, 10.13425798,  8.19584981, 13.43210386,
        5.38482786,  9.32599787, 14.16911116,  8.82848335, 11.68070192,
       15.57033379, 11.84410473, 13.06276807, 10.98222598,  6.53498206,
        9.9204947 ,  9.51373461, 24.21697767,  7.72986857, 12.42107899,
       17.65952642, 15.30134052, 11.47270716, 11.0350857 , 16.7024047 ,
        6.95562135])

In [73]:
lte = mean_squared_error(y_pred_lasso,y_test)
lte

3.641439660278575

In [74]:
lasso.score(X_train,y_train)

0.9093183106685329

Elastic Net

In [75]:
from sklearn.linear_model import ElasticNet
elastic = ElasticNet()
parameters = {'alpha':[1e-15,1e-10,1e-8,1e-4,1e-3,1e-2,1,5,10,20,30,100]}
elastic_regressor = GridSearchCV(elastic,parameters)
elastic_regressor.fit(X_train,y_train)


GridSearchCV(estimator=ElasticNet(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1,
                                   5, 10, 20, 30, 100]})

In [76]:
elastic_regressor.best_params_

{'alpha': 1}

In [77]:
elastic = ElasticNet(alpha=0.01)
elastic.fit(X_train,y_train)

ElasticNet(alpha=0.01)

In [78]:
y_pred_elastic = elastic.predict(X_test)

In [79]:
y_pred_elastic

array([16.586402  , 21.18549064, 21.66731146, 10.81048594, 22.25163555,
       13.31420282, 21.23826213,  7.38440465, 13.44030631, 15.19447632,
        9.01566567,  6.56992818, 14.41585343,  8.93561237,  9.56392271,
       12.10797318,  8.86077385, 16.25173792, 10.31045666, 18.83572422,
       19.81009787, 13.6747085 , 12.45155408, 21.58013901,  7.67464897,
        5.67152586, 20.95397442, 11.89337441,  9.13077249,  8.49447362,
       12.32274924,  9.99115106, 21.71913221, 12.64788135, 18.25365935,
       20.17378258, 14.20822564, 21.02783675, 10.91647318,  4.42734865,
        9.5940482 , 12.53183345, 10.14629887,  8.12978131, 13.33033574,
        5.27626244,  9.30549626, 14.15279198,  8.76023033, 11.67055177,
       15.66216243, 11.75402123, 13.21659238, 11.06227267,  6.41837431,
        9.84910774,  9.45785583, 24.32540514,  7.68924136, 12.30858524,
       17.5799634 , 15.27963482, 11.45671827, 11.12265678, 16.60062774,
        6.90638894])

In [80]:
ete = mean_squared_error(y_test,y_pred_elastic)
ete

3.727415438800228

In [81]:
elastic_score = elastic.score(X_train,y_train)
elastic_score

0.9095216571741495

In [82]:
print('Ridge: ', te)
print('Lasso: ', lte)
print('Elastic Net: ', ete)

Ridge:  3.720601493106788
Lasso:  3.641439660278575
Elastic Net:  3.727415438800228
